version: '3'
services:
    mjpeg-proxy:
        build:
            context: .
        image: itri-go/mjpeg-proxy
        container_name: mjpeg-proxy
        ports:
            - 54321:8080
        volumes:
            - './sources.json:/go/src/mjpeg-proxy/sources.json'
        restart: always
        command: "/go/src/mjpeg-proxy/mjpeg-proxy -sources sources.json"
